My code implemented for the LSTM model
XanX3601/deep_sentiment140 pull request #6
Opened 2020-05-13 12:24 UTC by ledinhcongminh

- The cleaning file I forgot to delete the UTF-8 BOM in the dataset (\xef \xbf \xbd ...) so I add it to the clean_dataset file.
- 0.2% of tweets are empty after cleaning. So I delete the empty tweet in the preload.py. In this file, I also take 10% of the data set for training (it already took me over an hour to scan with 10% of the data set).

I use Glove vector for embedding.

I used an LSTM model.

2020-05-13 19:36 UTC, ElieKadoche requested changes
Your code lacks of consistency. You need to respect Google docstring type and be carefull with typo error. You have to explain more your code in the docstring.

The modification on the clean_dataset requires another pull request I think, I found another way to do it.

Do you have any results with your model?

2020-05-13 19:36 UTC, ElieKadoche commented on clean_dataset.py
> -
Why do you remove the docstring?

2020-05-13 19:36 UTC, ElieKadoche commented on requirements.txt
> -nltk
Why do you remove these?

2020-05-13 19:36 UTC, ElieKadoche commented on clean_dataset.py
> -
Why do you remove these lines? There are part of the docstring.

2020-05-13 19:36 UTC, ElieKadoche commented on clean_dataset.py
> +
Why do you add an empty line here?

2020-05-13 19:36 UTC, ElieKadoche commented on clean_dataset.py
> +    np.save(utils.X_TEST_PATH, x_test_clean)
Typo error.

2020-05-13 19:36 UTC, ElieKadoche commented on create_datasets.py
> +    print("Done!")
Typo error.

2020-05-13 19:36 UTC, ElieKadoche commented on download_dataset.py
> +
Typo error, no empty line at the end.

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +@author: minh
Please remove these, this is a common project.

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +This file can be used as a model for all models.
This is true for the template, wrong the this model.

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +        pad_idx -  string representing the pad token
Please respect Google docstring types. [Here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) an example.

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +        Args:
Empty line between description and Args.

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +        packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, x_lengths) #pack the embeddings
For the comment, you need a space after the "#" and you need to begin your comment by a capital letter. I will not mark all of them in the code, but same commentary.

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +    save it in models/model_name/model_name.pt.
Empty line + args.

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +    #model = LSTM()
Do not keep commented lines in your code. It is either relevant or it is not.

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +
No empty line here...

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +    label - 0 or 1
Google docstring...

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +    All operations on the training dataset are allowed.
Again.

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +
Why so many empty lines?

2020-05-13 19:36 UTC, ElieKadoche commented on model.py
> +
Why so many empty lines?

2020-05-13 19:36 UTC, ElieKadoche commented on preload.py
> +"""
What is the purpose of this file?

2020-05-13 19:37 UTC, ElieKadoche commented on preload.py
> +"""
Ma fault, you said it in your commentary. We should not create another file but do it directly in the clean_dataset.py script.

2020-05-14 09:50 UTC, ledinhcongminh commented
Thanks for your remark !

For information, I used an LSTM model. I get an accuracy of 70% for training but only 54% for tests. I think that is also the structure of the LSTM. In fact, LSTM takes words from the transition sequence, from which I removed the punctuation (if I keep the punctuation, the result will be really worse). It may create a little overfit when the sentences get long due to lack of punctuation.

I think that with the CNN model or your other models will have better results!

Also, I think we should start reporting. May I create a link on the overleaf to share for three of us?

Thank you,

2020-05-14 20:59 UTC, ElieKadoche commented
As we discussed, I made some modifications. There are still modifications to do on your script, and important ones... I try to do it now.

You were absolutely right, there were empty samples. Good call.

2020-05-14 22:02 UTC, ElieKadoche commented
I made some modifications, but your LSTM model script contains too many architecture issues. Please try to correct them... In the `if __name__ == "__main__"` you should not put your code, only arguments and variables shared but the 3 functions. All your code need to be in the dedicated functions. You can of course create as many functions you like, and then use them in the main ones.

Also try to use better class than `torchtext.data.TabularDataset`. Create a csv is totaly useless since you can directly call `torchtext.data.Dataset`, etc.

2020-05-15 18:52 UTC, ElieKadoche approved these changes

2020-05-15 18:52 UTC, merged